# Form implementation generated from reading ui file 'MainWind.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 600)
        MainWindow.setStyleSheet("background-color: rgb(60, 60, 91);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(120, 470, 151, 51))
        self.pushButton_add.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"border-radius: 10;")
        self.pushButton_add.setObjectName("pushButton_add")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(120, 140, 501, 311))
        self.tableView.setStyleSheet("background-color: rgb(67, 67, 67);\n"
"border-radius: 10;")
        self.tableView.setObjectName("tableView")
        self.pushButton_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_edit.setGeometry(QtCore.QRect(290, 470, 161, 51))
        self.pushButton_edit.setStyleSheet("background-color: rgb(67, 67, 67);\n"
"border-radius: 10;")
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(470, 470, 151, 51))
        self.pushButton_delete.setStyleSheet("background-color: rgb(239, 0, 0);\n"
"border-radius: 10;")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_search.setGeometry(QtCore.QRect(20, 20, 661, 41))
        self.lineEdit_search.setStyleSheet("background-color: rgb(67, 67, 67);")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.pushButton_home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_home.setGeometry(QtCore.QRect(20, 540, 61, 41))
        self.pushButton_home.setStyleSheet("background-color: rgb(67, 67, 67);\n"
"border-radius: 20;")
        self.pushButton_home.setObjectName("pushButton_home")
        self.pushButton_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(20, 70, 61, 41))
        self.pushButton_search.setStyleSheet("border-radius: 20;\n"
"\n"
"background-color: rgb(127, 127, 190);")
        self.pushButton_search.setObjectName("pushButton_search")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add.setText(_translate("MainWindow", "добавить"))
        self.pushButton_edit.setText(_translate("MainWindow", "изменить"))
        self.pushButton_delete.setText(_translate("MainWindow", "удалить"))
        self.pushButton_home.setText(_translate("MainWindow", "Домой"))
        self.pushButton_search.setText(_translate("MainWindow", "Поиск"))
